export const routes = {
  baseRoute: '/',
  signIn: '/sign-in',
  signUp: '/sign-up',
  profile: '/profile',
  games: '/games',
  films: '/films',
  serials:'/serials',
  anime: '/anime',
  books: '/books',
  allUsers: '/allUsers',
  review: '/review',
  createReview: '/createReview',
  notFound: 'notFound',
}